// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package arfcasesqlc

import ()

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
