// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: offer.sql

package arfcasesqlc

import (
	"context"
)

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers (
  user_id,
  from_currency,
  to_currency,
  rate,
  amount
) VALUES (
  $1, $2, $3, $4, $5 
) RETURNING id, user_id, from_currency, to_currency, amount, rate, status, created_at
`

type CreateOfferParams struct {
	UserID       int64   `json:"user_id"`
	FromCurrency string  `json:"from_currency"`
	ToCurrency   string  `json:"to_currency"`
	Rate         float64 `json:"rate"`
	Amount       float64 `json:"amount"`
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, createOffer,
		arg.UserID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Rate,
		arg.Amount,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Amount,
		&i.Rate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOffer = `-- name: GetOffer :one
SELECT id, user_id, from_currency, to_currency, amount, rate, status, created_at FROM offers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOffer(ctx context.Context, id int64) (Offer, error) {
	row := q.db.QueryRowContext(ctx, getOffer, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Amount,
		&i.Rate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
