// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package arfcasesqlc

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
