definitions:
  api.approveOfferResponse:
    properties:
      offer:
        $ref: '#/definitions/arfcasesqlc.Offer'
      transfers:
        $ref: '#/definitions/arfcasesqlc.TransferTxResult'
    type: object
  api.authUserRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.authUserResponse:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
      refresh_token:
        type: string
      refresh_token_expires_at:
        type: string
      session_id:
        type: string
      user:
        $ref: '#/definitions/api.userResponse'
    type: object
  api.createUserRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.createWalletRequest:
    properties:
      currency:
        type: string
    required:
    - currency
    type: object
  api.offerRequest:
    properties:
      amount:
        type: number
      from_currency:
        minLength: 1
        type: string
      rate:
        type: number
      to_currency:
        minLength: 1
        type: string
    required:
    - amount
    - from_currency
    - rate
    - to_currency
    type: object
  api.userResponse:
    properties:
      username:
        type: string
    type: object
  arfcasesqlc.Offer:
    properties:
      amount:
        type: number
      created_at:
        type: string
      from_currency:
        type: string
      id:
        type: integer
      rate:
        type: number
      status:
        type: string
      to_currency:
        type: string
      user_id:
        type: integer
    type: object
  arfcasesqlc.Transfer:
    properties:
      amount:
        type: number
      created_at:
        type: string
      from_wallet_id:
        type: integer
      id:
        type: integer
      to_wallet_id:
        type: integer
    type: object
  arfcasesqlc.TransferTxResult:
    properties:
      transfer1:
        $ref: '#/definitions/arfcasesqlc.Transfer'
      transfer2:
        $ref: '#/definitions/arfcasesqlc.Transfer'
    type: object
  arfcasesqlc.Wallet:
    properties:
      balance:
        type: number
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: do test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: index sample
      tags:
      - example
  /auth:
    post:
      consumes:
      - application/json
      description: Auth user & return session token (jwt)
      parameters:
      - description: Auth user params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.authUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.authUserResponse'
      summary: Auth user
      tags:
      - user
  /offer/{id}/approve:
    post:
      consumes:
      - application/json
      description: Approve offer & complete converting currencies
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Offer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.approveOfferResponse'
      summary: Approve offer
      tags:
      - offer
  /offers:
    post:
      consumes:
      - application/json
      description: Create offer to convert currencies
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Create offer params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.offerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/arfcasesqlc.Offer'
      summary: Create offer
      tags:
      - offer
  /users:
    post:
      consumes:
      - application/json
      description: Create user with username & password
      parameters:
      - description: Create user params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.createUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.userResponse'
      summary: Create user
      tags:
      - user
  /wallets:
    get:
      consumes:
      - application/json
      description: List wallets of the user
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Page Id
        in: query
        name: page_id
        type: integer
      - description: Page Size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/arfcasesqlc.Wallet'
            type: array
      summary: List wallets
      tags:
      - wallet
    post:
      consumes:
      - application/json
      description: Create wallet for the user
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Create wallet params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.createWalletRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/arfcasesqlc.Wallet'
      summary: Create wallet
      tags:
      - wallet
swagger: "2.0"
